# For color names, see https://matplotlib.org/stable/gallery/color/named_colors.html

# Strobealign commits
commits:
  - name: "0.14.0"
    hash: "b3b8f485119ddb8c18d071f45819200cacbbf168"
    color: "tab:green"
  - name: "mcs-022a721"
    hash: "022a7219880eb842449da8a65874a547ac58f0d1"
    color: "black"
