datasets:
  - sim3
  - sim4
  - sim5

genomes:
  - drosophila
  - maize
  - CHM13
  - rye
#  - ecoli50

read-lengths:
  - 50
  - 75
  - 100
  - 150
  - 200
  - 300
  - 500

# Programs to run in addition to strobealign
programs:
 - bwamem
 - minimap2
 - xmapper

# Strobealign commits
# For color names, see https://matplotlib.org/stable/gallery/color/named_colors.html
commits:
  - key: "0.14.0"
    hash: "b3b8f485119ddb8c18d071f45819200cacbbf168"
    color: "tab:green"
    name: "strobealign 0.14.0"  # displayed in plots
#  - key: "0.15.0"
#    hash: "8f7988143f0000aed93026db2cd4e9e1ff7646f0"
#    color: "tab:olive"
#    name: "strobealign 0.15.0"  # displayed in plots

# Benchmarked for first revision of manuscript:
  - key: "mcs-022a721"
    hash: "022a7219880eb842449da8a65874a547ac58f0d1"
    color: "#333"
    name: "strobealign MCS1"

# - new MCS rescue
  - key: "mcs-feed434"
    hash: "feed43421c499e1110f166c0a56bb4e6a98c1196"
    color: "cyan"
    name: "strobealign MCS2"

# Rejected alternatives
#
# # - 1st syncmer always base
#   - key: "mcs-c338863"
#     hash: "c3388635cbdee834929c252bb6b3ea1a9e0c3b42"
#     color: "orangered"
#     name: "strobealign MCS1B"

# # - 1st syncmer always base
# # - new MCS rescue
#   - key: "mcs-bfce78a"
#     hash: "bfce78a6741f6ad05d04f3b1b41fdef1a3c18f24"
#     color: "tab:pink"
#     name: "strobealign MCS1BR"
